[package]
name = "ruby_fst"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7", features = ["rb-sys"] }
rb-sys = { version = "0.9", features = ["stable-api-compiled-fallback"] }
fst = { version = "0.4", features = ["levenshtein"] }
memmap2 = "0.9"
